version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout
git fetch origin
git checkout -b custom-build origin/custom-build
git merge main
git checkout main
git merge --no-ff custom-build
git push origin main
